version: '3'

volumes:
  pgsql-db-data:
    driver: local

services:
  app:
    image: rumbl
    hostname: app
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/home/elixir/app
    ports:
      - 4000:4000
    depends_on:
      - pgsql-db

  pgsql-db:
    image: postgres:11-alpine
    hostname: pgsql-db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres' 
    ports:
      - 5432:5432
    volumes:
      - pgsql-db-data:/var/lib/postgresql/data
  
  pgadmin4:
    hostname: pgadmin4
    image: dpage/pgadmin4
    ports:
     - 4001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'dev@elixir.com'
      PGADMIN_DEFAULT_PASSWORD: 'dev@1234'
    depends_on:
      - pgsql-db
